<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#savez" data-toc-modified-id="savez-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>savez</a></span></li><li><span><a href="#savez_compressed" data-toc-modified-id="savez_compressed-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>savez_compressed</a></span></li><li><span><a href="#Creating-Numpy-arrays-for-Data-variables" data-toc-modified-id="Creating-Numpy-arrays-for-Data-variables-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Creating Numpy arrays for Data variables</a></span></li><li><span><a href="#Saving-dimensions-and-data-variables" data-toc-modified-id="Saving-dimensions-and-data-variables-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Saving dimensions and data variables</a></span></li><li><span><a href="#Load-the-saved-data-npz-dataset" data-toc-modified-id="Load-the-saved-data-npz-dataset-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Load the saved data npz dataset</a></span></li><li><span><a href="#Load-all-dimensional-and-data-vareable" data-toc-modified-id="Load-all-dimensional-and-data-vareable-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Load all dimensional and data vareable</a></span></li><li><span><a href="#Save-it-as-xarray-Dataset" data-toc-modified-id="Save-it-as-xarray-Dataset-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Save it as xarray Dataset</a></span></li><li><span><a href="#Assign-attribute-information" data-toc-modified-id="Assign-attribute-information-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Assign attribute information</a></span></li><li><span><a href="#Saving-xarray-dataset-as-NetCDF-format" data-toc-modified-id="Saving-xarray-dataset-as-NetCDF-format-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Saving xarray dataset as NetCDF format</a></span></li></ul></div>

In [1]:
import numpy as np

In [2]:
import xarray as xr

- `np.savez`: Save several arrays into a single file in uncompressed `.npz format`  


- `np.savez_compressed`: Save several arrays into a single file in compressed `.npz format`   


- `np.load`: Load arrays from `.npz` files

In [3]:
a = np.array([1, 2, 3])

In [4]:
b = np.arange(10) 

In [5]:
c = np.linspace(0, 10, 10)

In [6]:
d = np.arange(12).reshape(3, 4)

In [7]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
a.shape, b.shape, c.shape, d.shape

((3,), (10,), (10,), (3, 4))

In [9]:
from numpy import savetxt

In [10]:
# save d numpy array to csv file
savetxt('d.csv', d, delimiter=',')

## savez

In [11]:
# save numpy array as `npz` uncompressed .npz format
from numpy import savez
savez('data_npz1.npz', a=a, b=b, c=c, d=d)

In [12]:
from numpy import load

In [13]:
data_npz1 = load('data_npz1.npz')

In [14]:
data_npz1.files

['a', 'b', 'c', 'd']

In [15]:
data_npz1['d'].shape

(3, 4)

In [16]:
data_npz1['d']

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## savez_compressed

In [17]:
from numpy import savez_compressed
savez_compressed('data_npz2.npz', a=a, b=b, c=c, d=d)

In [18]:
data_npz2 = load('data_npz2.npz')

In [19]:
data_npz2.files

['a', 'b', 'c', 'd']

In [20]:
data_npz2['d'].shape

(3, 4)

In [21]:
data_npz2['d']

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Creating Numpy arrays for Data variables

In [22]:
lats = np.arange(3, 16, 0.5)
lons = np.arange(33, 49, 0.5)

In [24]:
data = np.random.rand(len(lats), len(lons))

## Saving dimensions and data variables

In [25]:
savez_compressed('data_npz3.npz', lats=lats, lons=lons, data=data)

## Load the saved data npz dataset

In [26]:
data_npz3 = load('data_npz3.npz')

In [27]:
data_npz3.files

['lats', 'lons', 'data']

In [28]:
data_npz3['lons'].shape

(32,)

In [29]:
data_npz3['lats'].shape

(26,)

In [30]:
data_npz3['data'].shape

(26, 32)

In [31]:
data_npz3['data']

array([[7.40758210e-01, 8.56042813e-01, 9.06322754e-01, 1.98212912e-02,
        1.77621309e-01, 2.88495658e-01, 3.97212384e-01, 3.32267449e-01,
        2.51731946e-01, 1.63904384e-01, 3.52521607e-01, 8.99104496e-01,
        1.85255687e-03, 4.01585215e-01, 6.30785103e-01, 6.92750320e-01,
        5.72218720e-01, 4.02925754e-01, 9.91376950e-01, 4.23903473e-01,
        2.23209688e-01, 1.06730370e-01, 8.39176285e-01, 1.40751911e-01,
        7.48506118e-01, 3.56554698e-01, 5.37872431e-01, 3.70373543e-01,
        3.25185371e-01, 1.06558672e-01, 8.61222356e-01, 4.64769905e-01],
       [6.13383547e-01, 4.78108552e-01, 7.75395568e-01, 6.23675386e-01,
        2.28494487e-01, 8.91143551e-01, 8.69195916e-01, 9.63226050e-01,
        2.95243292e-01, 4.93832941e-02, 3.70415813e-01, 8.22695752e-01,
        6.18175463e-01, 6.40801921e-01, 3.24509413e-01, 8.58886767e-01,
        2.99330637e-01, 6.25977216e-01, 2.80100277e-01, 9.39184839e-01,
        4.30971286e-01, 1.66436916e-01, 3.87739879e-02, 7.91953

## Load all dimensional and data vareable

In [32]:
lon = data_npz3.f.lons
lat = data_npz3.f.lats
data_npz = data_npz3.f.data

## Save it as xarray Dataset

In [33]:
surf_dataset = xr.Dataset( data_vars= {'surf_data':(('lat', 'lon'), data_npz)},
                         coords={'lat':lat, 'lon':lon, })

In [34]:
surf_dataset

<xarray.Dataset>
Dimensions:    (lat: 26, lon: 32)
Coordinates:
  * lat        (lat) float64 3.0 3.5 4.0 4.5 5.0 ... 13.5 14.0 14.5 15.0 15.5
  * lon        (lon) float64 33.0 33.5 34.0 34.5 35.0 ... 47.0 47.5 48.0 48.5
Data variables:
    surf_data  (lat, lon) float64 0.7408 0.856 0.9063 ... 0.7944 0.7112 0.7217

## Assign attribute information

In [35]:
surf_dataset.lat.attrs['units'] = 'degrees_north'
surf_dataset.lat.attrs['standard_name'] = 'latitude'
surf_dataset.lat.attrs['long_name'] = 'latitude coordinate'
surf_dataset.lat.attrs['axis'] = 'Y'

In [36]:
surf_dataset.lon.attrs['units'] = 'degrees_east'
surf_dataset.lon.attrs['standard_name'] = 'longitude'
surf_dataset.lon.attrs['long_name'] = 'longitude coordinate'
surf_dataset.lon.attrs['axis'] = 'X'

In [37]:
surf_dataset.surf_data.attrs['units'] = 'kg/m3'
surf_dataset.surf_data.attrs['long_name'] = 'organic matter'
surf_dataset.surf_data.attrs['standard_name'] = 'matter density '

In [38]:
surf_dataset

<xarray.Dataset>
Dimensions:    (lat: 26, lon: 32)
Coordinates:
  * lat        (lat) float64 3.0 3.5 4.0 4.5 5.0 ... 13.5 14.0 14.5 15.0 15.5
  * lon        (lon) float64 33.0 33.5 34.0 34.5 35.0 ... 47.0 47.5 48.0 48.5
Data variables:
    surf_data  (lat, lon) float64 0.7408 0.856 0.9063 ... 0.7944 0.7112 0.7217

## Saving xarray dataset as NetCDF format

In [39]:
surf_dataset.to_netcdf('surface_dataset.nc')