<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#NumPy:-Creating-and-Manipulating-Numerical-Data" data-toc-modified-id="NumPy:-Creating-and-Manipulating-Numerical-Data-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>NumPy: Creating and Manipulating Numerical Data</a></span><ul class="toc-item"><li><span><a href="#Numpy-Importing-Conventions" data-toc-modified-id="Numpy-Importing-Conventions-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Numpy Importing Conventions</a></span></li><li><span><a href="#Creating-Arrays" data-toc-modified-id="Creating-Arrays-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Creating Arrays</a></span><ul class="toc-item"><li><span><a href="#Manual-construction-of-arrays" data-toc-modified-id="Manual-construction-of-arrays-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Manual construction of arrays</a></span></li><li><span><a href="#2-Dimensional-Arrays" data-toc-modified-id="2-Dimensional-Arrays-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>2-Dimensional Arrays</a></span></li><li><span><a href="#3-Dimensional-Arrays" data-toc-modified-id="3-Dimensional-Arrays-1.2.3"><span class="toc-item-num">1.2.3&nbsp;&nbsp;</span>3-Dimensional Arrays</a></span></li></ul></li><li><span><a href="#Functions-for-creating-arrays" data-toc-modified-id="Functions-for-creating-arrays-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Functions for creating arrays</a></span><ul class="toc-item"><li><span><a href="#Evenly-spaced-arrays:" data-toc-modified-id="Evenly-spaced-arrays:-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Evenly spaced arrays:</a></span></li><li><span><a href="#Common-Arrays" data-toc-modified-id="Common-Arrays-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>Common Arrays</a></span></li><li><span><a href="#Ones" data-toc-modified-id="Ones-1.3.3"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>Ones</a></span></li><li><span><a href="#Zeros" data-toc-modified-id="Zeros-1.3.4"><span class="toc-item-num">1.3.4&nbsp;&nbsp;</span>Zeros</a></span></li><li><span><a href="#Diagonal-Matrix" data-toc-modified-id="Diagonal-Matrix-1.3.5"><span class="toc-item-num">1.3.5&nbsp;&nbsp;</span>Diagonal Matrix</a></span></li></ul></li><li><span><a href="#Random-numbers" data-toc-modified-id="Random-numbers-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Random numbers</a></span><ul class="toc-item"><li><span><a href="#Uniform" data-toc-modified-id="Uniform-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Uniform</a></span></li><li><span><a href="#Gaussian" data-toc-modified-id="Gaussian-1.4.2"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>Gaussian</a></span></li></ul></li><li><span><a href="#Basic-Data-Types" data-toc-modified-id="Basic-Data-Types-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Basic Data Types</a></span><ul class="toc-item"><li><span><a href="#Intgers" data-toc-modified-id="Intgers-1.5.1"><span class="toc-item-num">1.5.1&nbsp;&nbsp;</span>Intgers</a></span></li><li><span><a href="#Floats" data-toc-modified-id="Floats-1.5.2"><span class="toc-item-num">1.5.2&nbsp;&nbsp;</span>Floats</a></span></li><li><span><a href="#Explicitly-specify-the-data-type" data-toc-modified-id="Explicitly-specify-the-data-type-1.5.3"><span class="toc-item-num">1.5.3&nbsp;&nbsp;</span>Explicitly specify the data-type</a></span></li><li><span><a href="#Other-Data-Types" data-toc-modified-id="Other-Data-Types-1.5.4"><span class="toc-item-num">1.5.4&nbsp;&nbsp;</span>Other Data Types</a></span></li><li><span><a href="#Complex-Number" data-toc-modified-id="Complex-Number-1.5.5"><span class="toc-item-num">1.5.5&nbsp;&nbsp;</span>Complex Number</a></span></li><li><span><a href="#Boolean-Number" data-toc-modified-id="Boolean-Number-1.5.6"><span class="toc-item-num">1.5.6&nbsp;&nbsp;</span>Boolean Number</a></span></li><li><span><a href="#String" data-toc-modified-id="String-1.5.7"><span class="toc-item-num">1.5.7&nbsp;&nbsp;</span>String</a></span></li></ul></li><li><span><a href="#Indexing-and-Slicing" data-toc-modified-id="Indexing-and-Slicing-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Indexing and Slicing</a></span><ul class="toc-item"><li><span><a href="#Reversing-a-sequence" data-toc-modified-id="Reversing-a-sequence-1.6.1"><span class="toc-item-num">1.6.1&nbsp;&nbsp;</span>Reversing a sequence</a></span></li><li><span><a href="#Indexing-Multidimensional-Arrays" data-toc-modified-id="Indexing-Multidimensional-Arrays-1.6.2"><span class="toc-item-num">1.6.2&nbsp;&nbsp;</span>Indexing Multidimensional Arrays</a></span></li><li><span><a href="#Indexing-by-Row" data-toc-modified-id="Indexing-by-Row-1.6.3"><span class="toc-item-num">1.6.3&nbsp;&nbsp;</span>Indexing by Row</a></span></li><li><span><a href="#Indexing-by-Column" data-toc-modified-id="Indexing-by-Column-1.6.4"><span class="toc-item-num">1.6.4&nbsp;&nbsp;</span>Indexing by Column</a></span></li><li><span><a href="#Slicing" data-toc-modified-id="Slicing-1.6.5"><span class="toc-item-num">1.6.5&nbsp;&nbsp;</span>Slicing</a></span></li><li><span><a href="#Combine-Assignment-and-Slicing" data-toc-modified-id="Combine-Assignment-and-Slicing-1.6.6"><span class="toc-item-num">1.6.6&nbsp;&nbsp;</span>Combine Assignment and Slicing</a></span></li></ul></li><li><span><a href="#Fancy-Indexing" data-toc-modified-id="Fancy-Indexing-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Fancy Indexing</a></span><ul class="toc-item"><li><span><a href="#Using-Boolean-Masks" data-toc-modified-id="Using-Boolean-Masks-1.7.1"><span class="toc-item-num">1.7.1&nbsp;&nbsp;</span>Using Boolean Masks</a></span></li><li><span><a href="#Indexing-with-an-array-of-integers" data-toc-modified-id="Indexing-with-an-array-of-integers-1.7.2"><span class="toc-item-num">1.7.2&nbsp;&nbsp;</span>Indexing with an array of integers</a></span></li></ul></li><li><span><a href="#Numpy-Help" data-toc-modified-id="Numpy-Help-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Numpy Help</a></span><ul class="toc-item"><li><span><a href="#Asking-For-Help" data-toc-modified-id="Asking-For-Help-1.8.1"><span class="toc-item-num">1.8.1&nbsp;&nbsp;</span>Asking For Help</a></span></li></ul></li><li><span><a href="#Exercise-1" data-toc-modified-id="Exercise-1-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Exercise 1</a></span></li><li><span><a href="#Numerical-operations-on-arrays" data-toc-modified-id="Numerical-operations-on-arrays-1.10"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>Numerical operations on arrays</a></span><ul class="toc-item"><li><span><a href="#Elementwise-Operations" data-toc-modified-id="Elementwise-Operations-1.10.1"><span class="toc-item-num">1.10.1&nbsp;&nbsp;</span>Elementwise Operations</a></span></li><li><span><a href="#Arithmetic-operates-elementwise" data-toc-modified-id="Arithmetic-operates-elementwise-1.10.2"><span class="toc-item-num">1.10.2&nbsp;&nbsp;</span>Arithmetic operates elementwise</a></span></li><li><span><a href="#Other-operations" data-toc-modified-id="Other-operations-1.10.3"><span class="toc-item-num">1.10.3&nbsp;&nbsp;</span>Other operations</a></span></li><li><span><a href="#Array-wise-comparisons" data-toc-modified-id="Array-wise-comparisons-1.10.4"><span class="toc-item-num">1.10.4&nbsp;&nbsp;</span>Array-wise comparisons</a></span></li><li><span><a href="#Transcendental-functions" data-toc-modified-id="Transcendental-functions-1.10.5"><span class="toc-item-num">1.10.5&nbsp;&nbsp;</span>Transcendental functions</a></span></li><li><span><a href="#Transposition" data-toc-modified-id="Transposition-1.10.6"><span class="toc-item-num">1.10.6&nbsp;&nbsp;</span>Transposition</a></span></li></ul></li><li><span><a href="#Basic-reductions" data-toc-modified-id="Basic-reductions-1.11"><span class="toc-item-num">1.11&nbsp;&nbsp;</span>Basic reductions</a></span><ul class="toc-item"><li><span><a href="#Sum-by-rows-and-by-columns" data-toc-modified-id="Sum-by-rows-and-by-columns-1.11.1"><span class="toc-item-num">1.11.1&nbsp;&nbsp;</span>Sum by rows and by columns</a></span></li><li><span><a href="#Extrema" data-toc-modified-id="Extrema-1.11.2"><span class="toc-item-num">1.11.2&nbsp;&nbsp;</span>Extrema</a></span></li><li><span><a href="#Statistics" data-toc-modified-id="Statistics-1.11.3"><span class="toc-item-num">1.11.3&nbsp;&nbsp;</span>Statistics</a></span></li><li><span><a href="#Array-shape-manipulation" data-toc-modified-id="Array-shape-manipulation-1.11.4"><span class="toc-item-num">1.11.4&nbsp;&nbsp;</span>Array shape manipulation</a></span></li><li><span><a href="#Flattening" data-toc-modified-id="Flattening-1.11.5"><span class="toc-item-num">1.11.5&nbsp;&nbsp;</span>Flattening</a></span></li><li><span><a href="#Reshaping" data-toc-modified-id="Reshaping-1.11.6"><span class="toc-item-num">1.11.6&nbsp;&nbsp;</span>Reshaping</a></span></li><li><span><a href="#Sorting-data" data-toc-modified-id="Sorting-data-1.11.7"><span class="toc-item-num">1.11.7&nbsp;&nbsp;</span>Sorting data</a></span></li><li><span><a href="#Rounding" data-toc-modified-id="Rounding-1.11.8"><span class="toc-item-num">1.11.8&nbsp;&nbsp;</span>Rounding</a></span></li></ul></li><li><span><a href="#Advanced-operations" data-toc-modified-id="Advanced-operations-1.12"><span class="toc-item-num">1.12&nbsp;&nbsp;</span>Advanced operations</a></span></li></ul></li></ul></div>

# NumPy: Creating and Manipulating Numerical Data

**NumPy**: is the core Python tool for performing numerical computations.

NumPy provides:  

    - array oriented computing  

    - multi-dimensional arrays  
    :
    - designed for scientific computation: useful linear algebra, Fourier transform, and random number capabilities
    
    - closer to hardware (efficiency)  

## Numpy Importing Conventions
The recommended convention to import numpy is:

In [1]:
# Import Numpy
import numpy as np

In [2]:
# this is just to make the output look better
np.set_printoptions(precision=3 , suppress= True) 

## Creating Arrays

### Manual construction of arrays

In [3]:
a = np.array([0, 1, 2, 3])

In [4]:
a

array([0, 1, 2, 3])

In [ ]:
# returns the shape of the array
a.shape

In [5]:
# returns no. of dimension
a.ndim

1

In [6]:
# returns the data type
type(a)

numpy.ndarray

### 2-Dimensional Arrays

In [7]:
# 2 x 3 array
b = np.array([[0, 1, 2], [3, 4, 5]])    

In [8]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
# returns no. of dimension
b.ndim

2

In [10]:
# returns the shape of the array
b.shape

(2, 3)

In [11]:
# returns the size of the first dimension
len(b)     

2

### 3-Dimensional Arrays

In [18]:
c = np.array([[[1,1,2], [2,3,3]], [[1,1,1], [1,1,1]], [[1,1,1], [1,1,1]]])

In [19]:
c

array([[[1, 1, 2],
        [2, 3, 3]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [20]:
# returns no. of dimension
c.ndim

3

In [21]:
# returns the shape of the array
c.shape

(3, 2, 3)

In [22]:
# returns the size of the first dimension
len(c)    

3

## Functions for creating arrays

### Evenly spaced arrays:

In [23]:
a = np.arange(10) # 0 .. n-1  (!)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
b = np.arange(1, 9, 2) # start, end (exclusive), step
b

array([1, 3, 5, 7])

In [29]:
c = np.linspace(0, 1, 6)   # start, end, num-points
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [30]:
d = np.linspace(0, 1, 6, endpoint=False)
d

array([0.   , 0.167, 0.333, 0.5  , 0.667, 0.833])

### Common Arrays

### Ones

In [32]:
a = np.ones((4, 3)) 
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Zeros

In [33]:
b = np.zeros((2, 2))
b

array([[0., 0.],
       [0., 0.]])

### Diagonal Matrix

In [34]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [36]:
e = np.diag(d)
e

array([1, 2, 3, 4])

## Random numbers

### Uniform

In [38]:
a = np.random.rand(4)       # uniform in [0, 1]
a  

array([0.001, 0.817, 0.992, 0.661])

### Gaussian

In [39]:
b = np.random.randn(4)      
b  

array([ 1.077, -0.3  , -0.459,  0.32 ])

## Basic Data Types

- NumPy auto-detects the data-type from the input.  
- In some instances, array elements are displayed with a trailing dot (e.g. 2. vs 2)

### Intgers

In [40]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

### Floats

In [41]:
b = np.array([1., 2., 3.])
b.dtype

dtype('float64')

### Explicitly specify the data-type

In [42]:
c = np.array([1, 2, 3], dtype=float)
c.dtype

dtype('float64')

### Other Data Types

### Complex Number 

In [43]:
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

dtype('complex128')

### Boolean Number 

In [44]:
e = np.array([True, False, False, True])
e.dtype

dtype('bool')

### String

In [46]:
f = np.array(['Bonjour', 'Hello', 'Hallooooo'])
f.dtype     

dtype('<U9')

## Indexing and Slicing

Indices begin at 0

In [47]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a[0]

0

In [49]:
a[2]

2

In [50]:
a[-1]

9

### Reversing a sequence

In [55]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Indexing Multidimensional Arrays

- In 2D, the first dimension corresponds to rows, the second to columns.
- a[0] is interpreted by taking all elements in the unspecified dimensions.

In [56]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [60]:
a[2, 2]

2

In [61]:
a[2, 1] = 10 # third line, second column

In [62]:
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

### Indexing by Row

In [63]:
a[0]

array([0, 0, 0])

In [64]:
a[1]

array([0, 1, 0])

### Indexing by Column

In [66]:
a[:,1]

array([ 0,  1, 10])

### Slicing

In [67]:
a = np.arange(10)
a 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a[:4]

array([0, 1, 2, 3])

In [69]:
a[1:3]

array([1, 2])

In [70]:
a[::2]

array([0, 2, 4, 6, 8])

In [71]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

### Combine Assignment and Slicing

In [72]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [74]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

## Fancy Indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing.

### Using Boolean Masks

In [75]:
np.random.seed(3)
a = np.random.randint(0, 21, 15)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])

In [76]:
(a % 3 == 0)

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True, False,  True, False, False])

In [77]:
mask = (a % 3 == 0)
mask

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True, False,  True, False, False])

In [78]:
extract_from_a = a[mask] 
extract_from_a           

array([ 3,  0,  9,  6,  0, 12])

In [79]:
a[a % 3 == 0] = -1
a

array([10, -1,  8, -1, 19, 10, 11, -1, 10, -1, -1, 20, -1,  7, 14])

### Indexing with an array of integers

In [83]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Indexing can be done with an array of integers, where the same index is repeated several time:

In [81]:
a[[2, 3, 2, 4, 2]] 

array([20, 30, 20, 40, 20])

In [84]:
a[[9, 7]] = -100
a

array([   0,   10,   20,   30,   40,   50,   60, -100,   80, -100])

## Numpy Help

On the web: https://numpy.org/doc/

### Asking For Help

In [85]:
np.add?

In [86]:
np.array?

In [ ]:
np.arr*?

In [ ]:
np.con*?

## Exercise 1

1) Create a simple one, two, and three  dimensional array.  
2) Use the functions len(), numpy.shape() on these arrays.  
3) Experiment with arange, linspace, ones, zeros, eye and diag.   
4) Create different kinds of arrays with random numbers.  
5 Look at the function `np.empty`. What does it do? When might this be useful?  

## Numerical operations on arrays

### Elementwise Operations

In [87]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [88]:
a + 1

array([2, 3, 4, 5])

In [89]:
2**a

array([ 2,  4,  8, 16])

### Arithmetic operates elementwise

In [90]:
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [91]:
a - b

array([-1.,  0.,  1.,  2.])

In [92]:
a * b

array([2., 4., 6., 8.])

### Other operations

In [93]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [94]:
a == b

array([False,  True, False,  True])

In [95]:
a > b

array([False, False,  True, False])

### Array-wise comparisons

In [98]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

In [99]:
np.logical_or(a, b)

array([ True,  True,  True, False])

In [100]:
np.logical_and(a, b)

array([ True, False, False, False])

### Transcendental functions

In [101]:
a = np.arange(5)

In [102]:
np.sin(a)

array([ 0.   ,  0.841,  0.909,  0.141, -0.757])

In [103]:
np.exp(a)

array([ 1.   ,  2.718,  7.389, 20.086, 54.598])

### Transposition

In [104]:
a = np.triu(np.ones((3, 3)), 1)   # see help(np.triu)
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [105]:
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [106]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
a.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

## Basic reductions

In [108]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [109]:
np.sum(x)

10

In [110]:
x.sum()

10

### Sum by rows and by columns

In [111]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [112]:
x.sum(axis=0)   # columns (first dimension)

array([3, 3])

In [113]:
x[:, 0].sum(), x[:, 1].sum()

(3, 3)

In [114]:
x.sum(axis=1)   # rows (second dimension)

array([2, 4])

In [115]:
x[0, :].sum(), x[1, :].sum()

(2, 4)

### Extrema

In [116]:
x = np.array([1, 3, 2])
x

array([1, 3, 2])

In [117]:
x.min()

1

In [118]:
x.max()

3

In [119]:
x.argmin()  # index of minimum

0

In [120]:
x.argmax()  # index of maximum

1

### Statistics

In [121]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])

In [122]:
x

array([1, 2, 3, 1])

In [123]:
y

array([[1, 2, 3],
       [5, 6, 1]])

In [124]:
x.mean()

1.75

In [125]:
np.median(x)

1.5

In [126]:
x.std()        

0.82915619758885

### Array shape manipulation

### Flattening

In [127]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [129]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [130]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

### Reshaping

In [131]:
a.shape

(2, 3)

In [132]:
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [133]:
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

### Sorting data

In [134]:
a = np.array([[4, 3, 5], [1, 2, 1]])
a

array([[4, 3, 5],
       [1, 2, 1]])

In [135]:
b = np.sort(a, axis=1)
b

array([[3, 4, 5],
       [1, 1, 2]])

### Rounding

In [136]:
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])
a

array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [137]:
b = np.around(a)
b                    # still floating-point


array([1., 2., 2., 2., 4., 4.])

In [138]:
c = np.around(a).astype(int)
c

array([1, 2, 2, 2, 4, 4])

## Advanced operations

In [139]:
p = np.poly1d([3, 2, -1])
p

poly1d([ 3,  2, -1])

In [140]:
p(0)

-1

In [141]:
p.roots

array([-1.   ,  0.333])

In [142]:
p.order

2